FrontEnd: Recover Password Form
HackYourFuture-CPH/fp-class19 pull request #102
Opened 2022-02-08 21:38 UTC by suvarna-ratna

# Description
This PR displays Recover Password Form... so if someone forgot password it would be easy for them to recover password using this component.
Please provide a short summary explaining what this PR is about.

Fixes #95

# How to test?
npm run storybook
Recover Password component / component
Please provide a short summary how your changes can be tested?

# Checklist

- [X] I have performed a self-review of my own code
- [X] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [X] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [X] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [X] This PR is ready to be merged and not breaking any other functionality

2022-02-09 13:27 UTC, santhoshboinapally approved these changes
its running on machine,

2022-02-09 13:47 UTC, Divyajg requested changes
Everything looks good on my machine. Just action is not working.

2022-02-09 13:47 UTC, Divyajg commented on src/client/components/RecoverPassword/RecoverPassword.stories.js
> +    onClick: { action: 'clicked' },
When I click submit, not giving any action in the storybook that's because you are using action here, but haven't imported it.

2022-02-10 11:16 UTC, suvarna-ratna commented on src/client/components/RecoverPassword/RecoverPassword.stories.js
> +    onClick: { action: 'clicked' },
Waiting for **kindly check your mail to reset your password** model . Once it done i will give link .

2022-02-12 11:36 UTC, Darya-s approved these changes
It is visible like in figma ...Good to go I think 👍

2022-02-17 11:57 UTC, JiuTak approved these changes
![image](https://user-images.githubusercontent.com/84173609/154476848-d906bf75-a4a8-4700-a883-9113011cc27c.png) good on my machine 👍

2022-02-17 19:06 UTC, merged