Feature/special offers
HackYourFuture-CPH/fp-class19 pull request #103
Opened 2022-02-09 10:43 UTC by Divyajg

# Description

This is the storybook model for special offer products.

Fixes # (31)

# How to test?

Pull the branch and run: npm run dev
checkout the storybook in the specialOffers component.

# Checklist

- [✔ ] I have performed a self-review of my own code
- [ ✔] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [✔ ] I have commented on my code, particularly in hard-to-understand areas, if your code was simple enough mark the box anyway
- [✔ ] I have made corresponding changes to the documentation, if your code was simple enough mark the box anyway
- [ ✔] This PR is ready to be merged and not breaking any other functionality

![image](https://user-images.githubusercontent.com/81112710/153182014-04362935-de85-40da-be7b-59a8ba89069f.png)

2022-02-09 14:22 UTC, NataliaS1994 approved these changes
Hej Divya! unfortunately, I'm not able to view the component in the storybook but the code looks clean to me!

2022-02-09 17:26 UTC, JiuTak approved these changes
it works/looks as it should on my local :)

2022-02-09 17:26 UTC, hparul requested changes

2022-02-09 17:26 UTC, hparul commented on src/client/components/SpecialOffers/Product.js
> +          {discountPrice} {currency}
component overall is looking good on storybook but instead of hard-coding the discount price, it would be better to set a condition that  as all products are on discount,then calculate and show the discounted price.

2022-02-09 17:29 UTC, saloumeh-67 approved these changes
it look really good in storybook :)

2022-02-10 10:17 UTC, Divyajg commented
@hparul Please review the changes.

2022-02-10 10:18 UTC, Divyajg commented
![image](https://user-images.githubusercontent.com/81112710/153386594-de065c8a-3d0e-4268-ac6b-c01f63e9fb79.png)

2022-02-10 11:18 UTC, suvarna-ratna commented
looking fine

2022-02-10 11:19 UTC, hparul approved these changes
looks nice on machine:) just use Math.round(discountedprice)

2022-02-10 11:19 UTC, suvarna-ratna approved these changes

2022-02-10 11:51 UTC, merged