Fix: LoginForm #139
HackYourFuture-CPH/fp-class19 pull request #140
Opened 2022-02-15 12:29 UTC by suvarna-ratna

change some part in this form ** Log In with Google**
 previously it was an image but now fix it to html button
Fixes # 139

# How to test?
npm run storybook

Please provide a short summary how your changes can be tested?

# Checklist

- [X] I have performed a self-review of my own code
- [X] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [X] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [X] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [X] This PR is ready to be merged and not breaking any other functionality

2022-02-18 13:56 UTC, Divyajg requested changes
I have made changes in the styles file as you requested, But why do you have files other than Login-component in this PR?
classNames can be more descriptive and specific, not just btn or btn2!

2022-02-19 08:49 UTC, saloumeh-67 reviewed
Thanks Suvarna , I think it looks the way it should.:)

2022-02-19 08:51 UTC, saloumeh-67 approved these changes

2022-02-21 14:02 UTC, santhoshboinapally approved these changes
Looks good to me 
![image](https://user-images.githubusercontent.com/64426776/154969917-29bc3d98-225d-4385-97cc-2c5da3f61d37.png)

2022-02-23 10:56 UTC, merged