Feature/orders endpoint
HackYourFuture-CPH/fp-class19 pull request #159
Opened 2022-02-18 10:59 UTC by JiuTak

# Description

Please provide a short summary explaining what this PR is about.

Fixes #99 

# How to test?
http://127.0.0.1:3000/api/documentation

Check ORDERS 

(I played with my local db and data and it looks like this)
![image](https://user-images.githubusercontent.com/84173609/154669858-77ec1b56-e56f-43c0-8a9d-030a654f8c3c.png)

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [x] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [x] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [x] This PR is ready to be merged and not breaking any other functionality

2022-02-18 20:04 UTC, Divyajg requested changes
Code looks good and working good too.
I requested couple of improvisations so that in the below cases it should respond with other than 200 code.

![jiu1](https://user-images.githubusercontent.com/81112710/154753475-29aee948-db09-40b3-9a52-4ac961a2eb27.JPG)
![jiu2](https://user-images.githubusercontent.com/81112710/154753552-2f91c5b7-e498-4d1b-9531-84c9c47d12e0.JPG)

2022-02-18 20:04 UTC, Divyajg commented on src/server/api/controllers/orders.controller.js
> +    throw new HttpError('Id should be a number', 400);
Response not showing 400!
I think the if condition can be more specific like typeof user_id, if user_id doesn't exist.

2022-02-18 20:04 UTC, Divyajg commented on src/server/api/routes/api-router.js
> +const orderRouter = require('./orders.router');
it can be ordersRouter ! What do you think?

2022-02-19 13:30 UTC, JiuTak commented on src/server/api/controllers/orders.controller.js
> +    throw new HttpError('Id should be a number', 400);
fixed :)

2022-02-19 13:31 UTC, JiuTak commented on src/server/api/routes/api-router.js
> +const orderRouter = require('./orders.router');
Typo, thanks :)

2022-02-20 19:37 UTC, closed without merging