Update to endpoint to delete favorites(products) of a user with error handlers/responses
HackYourFuture-CPH/fp-class19 pull request #207
Opened 2022-03-01 13:37 UTC by NataliaS1994

# Description

Setting the response status codes correctly in the controller.

Fixes #194 

# How to test?
npm run db:setup
npm run dev
http://localhost:3000/api/documentation/#/  --> SWAGER

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [ ] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [ ] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [ ] This PR is ready to be merged and not breaking any other functionality

2022-03-02 12:25 UTC, saloumeh-67 approved these changes
i opened it in swagger and check it in DB it all works :).

2022-03-03 12:59 UTC, dpfernandes requested changes

2022-03-03 12:59 UTC, dpfernandes commented on src/server/api/controllers/favorites.controller.js
> +    console.log('in add');
Please remove console log

2022-03-08 12:26 UTC, Divyajg reviewed
Code seems as it would work, I cannot test it in my machine as I have slightly changes DB.

2022-03-10 16:45 UTC, m-elshawa approved these changes
this is what shows up in case of succes. in case id is not a number it doesn't allow it, and in case of too big numbers it give the same message. Thus I'm not sure if this is how it should work. (error message don't come up)
![image](https://user-images.githubusercontent.com/49238049/157714368-23c99db4-af76-4af0-bcd9-e45e62fcb94a.png)

2022-03-10 20:46 UTC, miltonhultgren approved these changes
👍🏼

2022-03-11 11:21 UTC, merged