Add migrations for favorites  #28
HackYourFuture-CPH/fp-class19 pull request #29
Opened 2022-01-25 20:03 UTC by NataliaS1994

# Description

Please provide a short summary explaining what this PR is about.

Fixes # (issue)

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [ ] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [ ] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [ ] This PR is ready to be merged and not breaking any other functionality

2022-01-28 09:50 UTC, h09shais commented
Nice effort @NataliaS1994  !
Have you tried using `db:setup` from `package.json`?
Does `db:setup` follow your changes successfully :) ?

2022-01-28 14:21 UTC, NataliaS1994 commented
Thank you @h09shais. I tried to npm run db:setup but I received an error that no user_id found. I think it's because there is no user database delivered yet.

2022-01-28 14:44 UTC, h09shais commented
Create the user table and set the relation then 😀!

2022-01-28 17:51 UTC, senner007 requested changes

2022-01-28 17:51 UTC, senner007 commented on src/server/migrations/20200510015322_create_modules_schema.js
> -
See here for the discussion about the modules tables #18

Either remove the backend endpoint as well or keep everything including migrations and seeds

2022-01-30 12:55 UTC, pankaj28843 approved these changes
Tested on my machine, works well!

2022-01-30 12:55 UTC, merged