Save new user data
HackYourFuture-CPH/fp-class19 pull request #63
Opened 2022-02-02 14:49 UTC by Divyajg

# Description

Created an endpoint to save the new user data.

Fixes # (13)

# How to test?

Pull the Branch, 
run: npm run dev ,
go to: [http://localhost:3000/api/documentation], 
You will see: Users below the Modules,
got to: Postman and make a post request with body and you should see `{
    "successful": true
}`
go to database: you should see the new user created in the users table.

# Checklist

- [✔ ] I have performed a self-review of my own code
- [ ✔] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [ ✔] I have commented on my code, particularly in hard-to-understand areas, if your code was simple enough mark the box anyway
- [ ✔] I have made corresponding changes to the documentation, if your code was simple enough mark the box anyway
- [✔ ] This PR is ready to be merged and not breaking any other functionality

![newuser](https://user-images.githubusercontent.com/81112710/152176951-a0e1d767-d26f-4387-a774-d518d6b91a91.PNG)

2022-02-02 21:17 UTC, FlorentinaPetica approved these changes
Hey Divya, I've tested your pull request. It works as it should. I was able to see the documentation for swagger and I was also able to make a post request for a new users. It is ready for merge. Great job 👍

2022-02-02 21:45 UTC, senner007 requested changes

2022-02-02 21:45 UTC, senner007 commented on src/server/api/routes/api-router.js
> +router.use('/users', usersRouter);
this must be "/user" and not "/users"

2022-02-02 21:45 UTC, senner007 commented on src/server/api/routes/users.router.js
> +
Here you return 400, but your swagger docs says nothing of this

2022-02-02 21:47 UTC, senner007 commented on src/server/api/routes/users.router.js
> +
Remember to get into the habit of creating prs when the works is done everything is verified/tested

2022-02-02 21:54 UTC, saloumeh-67 reviewed
Thanks @Divyajg ,it works on my machine ;).

2022-02-02 22:27 UTC, senner007 requested changes

2022-02-02 22:27 UTC, senner007 commented on src/server/api/routes/users.router.js
> + *        description: The module to create.
This need fixing also. It must say 'The use to create'

2022-02-02 22:27 UTC, senner007 commented on src/server/api/routes/users.router.js
> + *            full_name:
Here you should insert a user props instead of "string".
Remember we test in swagger, not Postman

2022-02-03 20:29 UTC, suvarna-ratna approved these changes
Working as it should..

2022-02-05 10:49 UTC, Divyajg commented
@senner007 Please review the changes.

2022-02-05 16:46 UTC, senner007 commented on src/server/api/controllers/users.controller.js
> +const createUser = async (body) => {
Hi. You will want to add additional validation here. Remember a city can not be number, for instance.
Validation should happen in its own function. I suggest just creating an issue for now

2022-02-05 16:48 UTC, senner007 approved these changes
👍
Hi. look at the changes I made and verify yourself. Add additional validation later.

2022-02-05 16:48 UTC, senner007 commented on src/server/api/routes/users.router.js
> + */
Here I made some corrections. This is not optimal but we can refactor later

2022-02-05 16:48 UTC, senner007 commented on src/server/api/controllers/users.controller.js
> +  await knex('users').insert({
Hi. You will want to add additional validation here. Remember a city can not be number, for instance.
Validation should happen in its own function. I suggest just creating an issue for now

2022-02-05 22:47 UTC, merged