Feature/favoritelist component
HackYourFuture-CPH/fp-class19 pull request #68
Opened 2022-02-03 12:28 UTC by hparul

# Description

This PR is about creating favourite list component

Fixes # (https://github.com/HackYourFuture-CPH/fp-class19/issues/17)

# How to test?
npm run storybook

Please provide a short summary how your changes can be tested?

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [ ] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [ ] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [ ] This PR is ready to be merged and not breaking any other functionality

2022-02-05 07:36 UTC, Divyajg reviewed
Storybook is working on my machine, but every counter change reflects on every product, not the specific product.

2022-02-05 08:14 UTC, suvarna-ratna requested changes
Pls remove Package.json changes from this PR

2022-02-06 11:32 UTC, senner007 requested changes

2022-02-06 11:32 UTC, senner007 commented on package.json
>      "@storybook/addon-knobs": "^6.1.14",
remove changes to package.json

2022-02-06 11:32 UTC, senner007 commented on src/client/components/FavouriteList/FavouriteList.js
> +
This component must be broken down into sub components.
See here https://reactjs.org/docs/thinking-in-react.html

2022-02-06 11:32 UTC, senner007 commented on src/client/components/FavouriteList/FavouriteList.js
> +        {productList.map((product) => {
Preferrably dont nest logic within the jsx ( the productList mapping ). It makes it harder to read.
Image you open a component and you have 5 seconds to read and understand what it does.

2022-02-08 20:22 UTC, hparul commented on package.json
>      "@storybook/addon-knobs": "^6.1.14",
done

2022-02-09 13:01 UTC, hparul commented on src/client/components/FavouriteList/FavouriteList.js
> +
done

2022-02-09 13:11 UTC, Divyajg commented on src/client/components/FavouriteList/ProductQuantity.js
> +    setCounter(counter - 1);
The counter is going to negative numbers. Try to give a condition here, so that the -counter will stop at count 1.

2022-02-09 13:12 UTC, Divyajg commented on src/client/components/FavouriteList/ProductQuantity.js
> +  const [counter, setCounter] = useState(0);
I suggest starting the counter at 1, not 0. Because we cannot add 0 qty to the cart, agree?

2022-02-09 15:20 UTC, hparul commented on src/client/components/FavouriteList/ProductQuantity.js
> +  const [counter, setCounter] = useState(0);
yes,correct.done the changes.Thanks

2022-02-09 15:36 UTC, merged